robot_name: 'anymal_d'

joint_names: &jn ["LF_HAA", "LF_HFE", "LF_KFE", "LH_HAA", "LH_HFE", "LH_KFE", "RF_HAA", "RF_HFE", "RF_KFE", "RH_HAA", "RH_HFE", "RH_KFE"]
base_name: "base"

state_topic: "anymal_d/state"
command_topic: "anymal_d/command"
change_controller_topic: "anymal_d/change_controller"
gridmap_topic: "elevation_mapping/elevation_map_raw"
gridmap_layer: "elevation"
contact_topics: ["/lf_foot_contact", "/rf_foot_contact", "/lh_foot_contact","/rh_foot_contact"] 


marker_topic: "markers"
odom_frame: "odom"

state_publisher:
  update_rate: 400 # Hz

static_controller:
  stand_controller:
    joint_angles: [0.0, 0.4, -0.8, 0.0, -0.4, 0.8, 0.0, 0.4, -0.8, 0.0, -0.4, 0.8] # LF, LH, RF, RH
  sit_controller:
    joint_angles: [0.0, 1.5, -2.6, 0.0, -1.5, 2.6, 0.0, 1.5, -2.6, 0.0, -1.5, 2.6] # LF, LH, RF, RH
  kp: 400
  kd: 5
  interpolation_time: 1.0 # s
  rate: 50 # Hz

bob_controller:
  blind: false
  kp: 80.0
  kd: 2.0
  model_path: "package://tbai_rl_perceptive/models/anymal_model_action12_anymal_d_perceptive.pt"

  default_stance: [
    [ 0.00790786,  0.05720384, -0.573],
    [-0.00790786,  0.05720384, -0.573],
    [ 0.00790786, -0.05720384, -0.573],
    [-0.00790786, -0.05720384, -0.573],
  ]

  ik:
    d2: 0.20875
    a3: 0.285
    a4: 0.404999816790082

  cpg:
    period: 0.6
    time_offsets: [0.0, 0.3, 0.3, 0.0]  # LF, LH, RF, RH
    swing_height: 0.2

reference_generator:
  type: "joystick"

  joystick:
    topic: "joy"
    ramped_velocity: 5.0
    x_index: 1
    y_index: 0
    yaw_index: 3
    x_scale: 1.0
    y_scale: 0.5
    yaw_scale: 0.5

  twist:
    topic: "cmd_vel"


anymal_d:
  joint_controller:
      type: tbai_gazebo/JointController
      joints: *jn

contact_sensor:
  update_rate: 20 # Hz